import '../models/driver.dart';
import '../models/team.dart';

class TeamManager {
  static List<Team> getPresetTeams() {
    return [
      // 1. ريد بول
      Team(
        id: 'red_bull',
        name: 'ريد بول',
        country: 'النمسا',
        foundingYear: 2005,
        budget: 160000000,
        carPerformance: 94,
        enginePower: 95,
        aerodynamics: 94,
        reliability: 88,
        championshipTarget: 1,
        budgetTarget: 1,
        developmentFocus: 1,
        reputation: 96,
        driver1: Driver(
          id: 'max_verstappen',
          name: 'ماكس فيرستابين',
          nationality: 'هولندي',
          age: 27,
          speed: 98,
          consistency: 92,
          overtaking: 96,
          defense: 89,
          wetWeather: 93,
          experience: 88,
          salary: 30000000,
        ),
        driver2: Driver(
          id: 'liam_lawson',
          name: 'ليام لوسون',
          nationality: 'نيوزيلندي',
          age: 22,
          speed: 88,
          consistency: 84,
          overtaking: 85,
          defense: 82,
          wetWeather: 80,
          experience: 60,
          salary: 8000000,
        ),
      ),

      // 2. فيراري
      Team(
        id: 'ferrari',
        name: 'فيراري',
        country: 'إيطاليا',
        foundingYear: 1950,
        budget: 240000000,
        carPerformance: 92,
        enginePower: 91,
        aerodynamics: 90,
        reliability: 88,
        championshipTarget: 1,
        budgetTarget: 2,
        developmentFocus: 1,
        reputation: 94,
        driver1: Driver(
          id: 'charles_leclerc',
          name: 'شارل لوكلير',
          nationality: 'موناكي',
          age: 28,
          speed: 94,
          consistency: 91,
          overtaking: 90,
          defense: 87,
          wetWeather: 89,
          experience: 85,
          salary: 25000000,
        ),
        driver2: Driver(
          id: 'lewis_hamilton',
          name: 'لويس هاملتون',
          nationality: 'بريطاني',
          age: 40,
          speed: 93,
          consistency: 97,
          overtaking: 90,
          defense: 85,
          wetWeather: 90,
          experience: 100,
          salary: 40000000,
        ),
      ),

      // 3. مرسيدس
      Team(
        id: 'mercedes',
        name: 'مرسيدس',
        country: 'ألمانيا',
        foundingYear: 2010,
        budget: 150000000,
        carPerformance: 91,
        enginePower: 92,
        aerodynamics: 89,
        reliability: 90,
        championshipTarget: 2,
        budgetTarget: 2,
        developmentFocus: 0,
        reputation: 91,
        driver1: Driver(
          id: 'george_russell',
          name: 'جورج راسل',
          nationality: 'بريطاني',
          age: 27,
          speed: 91,
          consistency: 90,
          overtaking: 89,
          defense: 88,
          wetWeather: 86,
          experience: 75,
          salary: 12000000,
        ),
        driver2: Driver(
          id: 'kimi_antonelli',
          name: 'كيمي أنتونيللي',
          nationality: 'إيطالي',
          age: 18,
          speed: 85,
          consistency: 80,
          overtaking: 82,
          defense: 78,
          wetWeather: 80,
          experience: 50,
          salary: 5000000,
        ),
      ),

      // 4. ماكلارين
      Team(
        id: 'mclaren',
        name: 'ماكلارين',
        country: 'بريطانيا',
        foundingYear: 1963,
        budget: 130000000,
        carPerformance: 88,
        enginePower: 88,
        aerodynamics: 89,
        reliability: 85,
        championshipTarget: 3,
        budgetTarget: 3,
        developmentFocus: 1,
        reputation: 87,
        driver1: Driver(
          id: 'lando_norris',
          name: 'لاندو نوريس',
          nationality: 'بريطاني',
          age: 25,
          speed: 93,
          consistency: 91,
          overtaking: 90,
          defense: 87,
          wetWeather: 84,
          experience: 80,
          salary: 18000000,
        ),
        driver2: Driver(
          id: 'oscar_piastri',
          name: 'أوسكار بياستري',
          nationality: 'أسترالي',
          age: 24,
          speed: 89,
          consistency: 87,
          overtaking: 86,
          defense: 83,
          wetWeather: 80,
          experience: 65,
          salary: 8000000,
        ),
      ),

      // 5. أستون مارتن
      Team(
        id: 'aston_martin',
        name: 'أستون مارتن',
        country: 'بريطانيا',
        foundingYear: 1913,
        budget: 140000000,
        carPerformance: 89,
        enginePower: 90,
        aerodynamics: 88,
        reliability: 87,
        championshipTarget: 3,
        budgetTarget: 4,
        developmentFocus: 1,
        reputation: 88,
        driver1: Driver(
          id: 'fernando_alonso',
          name: 'فرناندو ألونسو',
          nationality: 'إسباني',
          age: 43,
          speed: 92,
          consistency: 90,
          overtaking: 89,
          defense: 88,
          wetWeather: 87,
          experience: 100,
          salary: 22000000,
        ),
        driver2: Driver(
          id: 'lance_stroll',
          name: 'لانس سترول',
          nationality: 'كندي',
          age: 28,
          speed: 88,
          consistency: 86,
          overtaking: 85,
          defense: 84,
          wetWeather: 82,
          experience: 80,
          salary: 10000000,
        ),
      ),

      // 6. ألباين
      Team(
        id: 'alpine',
        name: 'ألباين',
        country: 'فرنسا',
        foundingYear: 1976,
        budget: 100000000,
        carPerformance: 83,
        enginePower: 85,
        aerodynamics: 84,
        reliability: 86,
        championshipTarget: 5,
        budgetTarget: 5,
        developmentFocus: 1,
        reputation: 80,
        driver1: Driver(
          id: 'pierre_gasly',
          name: 'بيير غاُسلي',
          nationality: 'فرنسي',
          age: 29,
          speed: 90,
          consistency: 88,
          overtaking: 87,
          defense: 86,
          wetWeather: 85,
          experience: 90,
          salary: 12000000,
        ),
        driver2: Driver(
          id: 'jack_doohan',
          name: 'جاك دوهان',
          nationality: 'أسترالي',
          age: 21,
          speed: 86,
          consistency: 82,
          overtaking: 85,
          defense: 80,
          wetWeather: 80,
          experience: 60,
          salary: 5000000,
        ),
      ),

      // 7. هاas
      Team(
        id: 'haas',
        name: 'هاس',
        country: 'الولايات المتحدة',
        foundingYear: 1984,
        budget: 90000000,
        carPerformance: 80,
        enginePower: 82,
        aerodynamics: 80,
        reliability: 84,
        championshipTarget: 6,
        budgetTarget: 6,
        developmentFocus: 1,
        reputation: 75,
        driver1: Driver(
          id: 'esteban_ocon',
          name: 'إستيبان أوكون',
          nationality: 'فرنسي',
          age: 29,
          speed: 89,
          consistency: 88,
          overtaking: 86,
          defense: 85,
          wetWeather: 85,
          experience: 95,
          salary: 15000000,
        ),
        driver2: Driver(
          id: 'oliver_bearman',
          name: 'أوليفر بيرمان',
          nationality: 'بريطاني',
          age: 20,
          speed: 87,
          consistency: 84,
          overtaking: 85,
          defense: 82,
          wetWeather: 83,
          experience: 70,
          salary: 6000000,
        ),
      ),

      // 8. RB (فريق شقيق لريد بول)
      Team(
        id: 'rb',
        name: 'فريق RB',
        country: 'اليابان / قاعدة رياضية',
        foundingYear: 2005,
        budget: 70000000,
        carPerformance: 78,
        enginePower: 80,
        aerodynamics: 78,
        reliability: 82,
        championshipTarget: 8,
        budgetTarget: 8,
        developmentFocus: 1,
        reputation: 70,
        driver1: Driver(
          id: 'yuki_tsunoda',
          name: 'يوكي تسونودا',
          nationality: 'ياباني',
          age: 25,
          speed: 86,
          consistency: 84,
          overtaking: 85,
          defense: 82,
          wetWeather: 80,
          experience: 70,
          salary: 6000000,
        ),
        driver2: Driver(
          id: 'isack_hadjar',
          name: 'إيساك هادجار',
          nationality: 'فرنسي',
          age: 20,
          speed: 85,
          consistency: 83,
          overtaking: 84,
          defense: 80,
          wetWeather: 82,
          experience: 60,
          salary: 5000000,
        ),
      ),

      // 9. ويليامز
      Team(
        id: 'williams',
        name: 'ويليامز',
        country: 'بريطانيا',
        foundingYear: 1977,
        budget: 80000000,
        carPerformance: 75,
        enginePower: 78,
        aerodynamics: 74,
        reliability: 80,
        championshipTarget: 8,
        budgetTarget: 8,
        developmentFocus: 0,
        reputation: 68,
        driver1: Driver(
          id: 'alex_albon',
          name: 'أليكس ألبون',
          nationality: 'تايلاندي',
          age: 29,
          speed: 83,
          consistency: 86,
          overtaking: 81,
          defense: 80,
          wetWeather: 78,
          experience: 75,
          salary: 4000000,
        ),
        driver2: Driver(
          id: 'carlos_sainz',
          name: 'كارلوس ساينز',
          nationality: 'إسباني',
          age: 30,
          speed: 88,
          consistency: 87,
          overtaking: 86,
          defense: 85,
          wetWeather: 86,
          experience: 90,
          salary: 10000000,
        ),
      ),

      // 10. ساوبر (Kick Sauber)
      Team(
        id: 'sauber',
        name: 'ساوبر',
        country: 'سويسرا',
        foundingYear: 1970,
        budget: 85000000,
        carPerformance: 76,
        enginePower: 78,
        aerodynamics: 77,
        reliability: 82,
        championshipTarget: 7,
        budgetTarget: 7,
        developmentFocus: 1,
        reputation: 72,
        driver1: Driver(
          id: 'nico_hulkenberg',
          name: 'نيكو هولكنبيرغ',
          nationality: 'ألماني',
          age: 37,
          speed: 85,
          consistency: 88,
          overtaking: 84,
          defense: 86,
          wetWeather: 87,
          experience: 100,
          salary: 12000000,
        ),
        driver2: Driver(
          id: 'gabriel_bortoleto',
          name: 'غابرييل بورتوليتو',
          nationality: 'برازيلي',
          age: 21,
          speed: 86,
          consistency: 83,
          overtaking: 85,
          defense: 82,
          wetWeather: 80,
          experience: 65,
          salary: 5000000,
        ),
      ),
    ];
  }

  static List<Map<String, dynamic>> getLegacyTeams() {
    return getPresetTeams().map((team) => {
      'id': team.id,
      'name': team.name,
      'budget': team.budget,
      'carPerformance': team.carPerformance,
      'reputation': team.reputation,
    }).toList();
  }
}
